### ISSUE TITLE
是否有计划添加 "scrollHold" 属性，避免轻微接触时造成的页面震动

### ISSUE THREAD

**Issue by CodingMonkeyzh** [houyulei/ReactSwipe#1]
个人觉得 [Swipe](https://github.com/houyulei/Swipe) 中新增的这个参数很实用，建议在这个组件也加上此特性。

> 新加参数scrollHold,当滑动距离大于scrollHold时,才进入scrolling滚动.避免轻微接触时造成的页面震动.

**Comment by houyulei** [comment]
ReactSwipe基于[Swipe](https://github.com/houyulei/Swipe),所以是包含这个特性的。
